spring.application.name=auth-service

# Server
server.port=8081

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/oblms_auth
spring.datasource.username=root
spring.datasource.password=Lucky@75
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Gmail SMTP for OTP (App Password saved here so it works in every run)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=250320100031@cutm.ac.in
spring.mail.password=aigecjlstcpqaccm
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true